= Counterclockwise ChangeLog 
Laurent Petit <laurent dot petit at gmail dot com>
:sectanchors:
:sectlinks:
:source-highlighter: coderay
:experimental:
:toc: 
:toc-title!:
:toclevels: 0

== Changes between Counterclockwise 0.22.0 and 0.23.0

`0.23.0` released on January 23, 2014

Fixes the compatibility problems with Eclipse Indigo!

== Counterclockwise/Standalone

- It is now possible to use the usual Software Update Site to upgrade a Counterclockwise/Standalone install with new versions of Counterclockwise.
- The version is now displayed in the Counterclockwise About Dialog.
- The Products zips filenames now contain the version

== Documentation

=== Installation section

- now mentions the Counterclockwise version number (in the text, and the corresponding links)

== Changes between Counterclockwise 0.21.0 and 0.22.0

`0.22.0` released on January 10, 2014

=== Leiningen Upgrade

The embedded Leiningen has been upgraded from version `2.1.2` to a patched `2.3.4`.

=== Automatic opening of REPL Views

The patch applied to Leiningen `2.3.4` relates to the `lein repl` task: in addition to displaying a human readable info about the nREPL server's port & host, it appends a nREPL URL.

Before:

  nREPL server started on port 61149 on host 127.0.0.1

After:

  nREPL server started on port 61149 on host 127.0.0.1 - nrepl://127.0.0.1:61149

This nREPL URL is automatically converted to an hyperlink in the Console View. +
And even more: the first time a nREPL link appears in a Console View, Counterclockwise automatically opens a REPL View for it!

=== Shortcut for starting a Headless Leiningen REPL

kbd:[Alt+L H] is a shortcut for launching a headless leiningen REPL. It is similar to doing kbd:[Alt+L L] + typing `your-project $ lein repl :headless`.

=== Shortcut for resetting the Project Classpath

kbd:[Alt+L R] resets the project classpath, using Leiningen to compute the classpath.

=== Leiningen classpath more permissive

Resolving leiningen classpath is now more permissive

==== Overlapping source paths are allowed
Overlapping `:source-paths`, `:resource-paths`,  `:test-paths` and/or `:java-source-paths` are accepted.
Counterclockwise resolves the conflict by adding the required exclusions to its source classpath entries.

For instance, if you have declared (explicitly or implicitly) both `resources`  and `resources/public` as resource paths,
Counterclockwise will create 2 source path entries: 

- one for `resources/public`, 
- and one for `resources`, with an exclusion filter for its `public` subfolder

==== Missing source paths are not reported as errors anymore
All paths are marked as 'optional' so that if folders for these paths are missing, no exception is reported by Eclipse.


== Changes between Counterclockwise 0.20.0 and 0.21.0

`0.21.0` released on January 9, 2014

=== General purpose Leiningen task invoker

Addition of a new command, kbd:[Alt+L L] for launching a popup allowing to enter an arbitry leiningen command.

It allows you to launch arbitrary leiningen tasks from within Eclipse.

See Documentation: http://doc.ccw-ide.org/documentation.html#_generic_command_launcher

=== New Clojure Project Wizard ===

The Wizard has been modified to simplify the understanding of its fields. Especially, the "Use default location" field has been replaced with a "Create project folder in:" field, and its meaning has changed from "ask the user for the project's folder on the filesystem" to "ask the user for the project's parent folder on the filesystem (assuming that the project folder will be the project name)". This is wayyy more intuitive.

The "Working Sets" section of the Wizard has been removed. Instead, the newly created project is automatically added to the currently active Working Sets.

=== Editor responsiveness

Timeouts have been added for all Counterclockwise interactions with the nREPL connection of a REPL View. +
Nothing should prevent the user to type in an Editor. Counterclockwise should gracefully downgrade its features instead. This is a step in this direction.

- Code completion: 1 second timeout. If timeout occurs twice for a given REPL, it won't be used anymore (only static code completion will take place).
- Text Hover: 1 second timeout.
- Hyperlink Detection: 1 second timeout.
- Namespace Browser: 15 seconds timeout.
- REPL: 15 seconds timeout at some initialization usage of the nrepl client

=== "Load File" in Editor

"Load File" action now works for editors opened via menu:File[Open File...] (aka arbitrary file on the filesystem, not necessarily living inside a project inside the Eclipse Workspace)

=== User plugins

It is possible to contribute Counterclockwise User Plugins inside folder `~/.ccw`. +
This will be a way both:
- for users to contribute / experiment more easily to Counterclockwise
- for the Counterclockwise team to provide beta features for rapid user feedback

INFO: a User Plugin is dynamic. To remove it, just remove it.

A whole new section of the documentation has been added concerning User plugins. See http://doc.ccw-ide.org/documentation.html#_user_plugins for the full story.

WARNING: Works only with Eclipse 4 and CCW/Standalone.

=== Experimental User Plugin: "Plugin additions"

This plugin adds commands for managing User Plugins (sorry, it's a little bit `meta`):

- kbd:[Alt+U S] - re[S]tart user plugins (will reload all user plugins code)
- kbd:[Alt+U N] - create a [N]ew user plugin (will prompt you for a plugin name, create the plugin folder/file, a project in the workspace, and open a repl connection to your Eclipse instance)
- kbd:[Alt+U I] - Import all user plugins present in `~/.ccw` as projects in workspace

The plugin is available as a Gist, you can examine its content here https://gist.github.com/laurentpetit/7924786 and then clone its repository https://gist.github.com/7924786.git in `~/.ccw/plugin-additions`

[source,bash]
git clone https://gist.github.com/7924786.git ~/.ccw/plugin-additions
# Restart your Eclipse

=== nREPL Version Update

The embedded nREPL client in Counterclockwise, and which is also used to serve as nREPL client when the project does not declare a dependency on nREPL (the majority of the cases) has been upgraded from version `0.2.1` to `0.2.3`. 

=== Bug fix 

- Explicitly ask the user for confirmation before launching a second process for the same project

=== Leiningen based Launcher

The code is there, but not active at the moment (needs more love / hammock)

=== CCW/Standalone

Changed the URL for downloading the stable standalone versions: http://standalone.ccw-ide.org/

Increased the MaxPermSize value from 128Mb to 256Mb, since there has been reports that 128Mb weren't enough, e.g. when invoking the `New Clojure Project` Wizard.

Fix of an issue with the pre-referenced software update sites (was still pointing to Indigo instead of Kepler)

Moar sensible default preferences:

- Editors
** line numbers displayed in the margin
** 80 chars column displayed
** tabs automatically replaced by spaces when typing
- Worskpace
** automatic refresh of the Workspace resources without asking the user


== Changes between Counterclockwise 0.12.3 and 0.20.0

`0.20.0` released on October 10, 2013

=== TL;DR

- `0.20.0` introduces **no breaking change**
- New Software Update Site http://updatesite.ccw-ide.org/stable
- Editor: new awesome `autoshift` feature, slurp/barf paredit commands support
- Lots of changes to fix stability concerns and various issues

=== Build Process totally rewritten

For people wanting to build Counterclockwise from scratch, or to work with Counterclockwise.

The Build Process now uses http://maven.apache.org[Maven] + http://www.eclipse.org/tycho[Tycho].

- It is now fully automated, from fetching Eclipse or non Eclipse dependencies, to building an update site for the codebase, to building Standalone Counterclockwise products for the codebase.

In a nutshell:

  git clone https://github.com/laurentpetit/ccw
  cd ccw
  mvn verify
  cd ccw.product/target/products # the products for Windows / Linux / OS X
  cd ../../../ccw.updatesite/target/repository # the Software Update Site 

For more information on installing a full-fledged dev environment, see the Wiki Page https://code.google.com/p/counterclockwise/wiki/HowToBuild[How To Build]

=== New Software Update Site

The software update site has been updated to its new location:

- Stable Versions: http://updatesite.ccw-ide.org/stable
- Beta Versions: http://updatesite.ccw-ide.org/beta

For more information on the available Software Update Sites and their retention policies, and more, see the Wiki Page https://code.google.com/p/counterclockwise/wiki/UpdateSites[Update Sites]

=== Editor

==== Reindent Selection
Reindent Selection has been implemented. Trigger it via `Ctrl+i` on Windows/Linux, `Cmd+i` on OSX.

==== Autoshift
While you type, the code on the following lines which depends upon the code on the current line is shifted to the right or to the left. More spaces/less spaces are added/removed automatically.

* For instance, if you have the following manually indented code (note that the call to the `cond` macro is indented 4 extra spaces to the right):
+
[source,clojure]
(defn foo [bar baz]
       (cond
         cond1
           expr1
         cond2
           expr2
         :else
           default-expr))

* You can fix the whole indentation by either placing the cursor anywhere in the `(cond` line and typing Tab, or in front of `(cond` and typing Backspace 2 times:
+
[source,clojure]
(defn foo [bar baz]
  (cond
    cond1
      expr1
    cond2
      expr2
    :else
      default-expr))

* Before the AutoShift feature, you would either have to indent each line manually, or select the whole `(cond..)` form and type `Ctrl+i` (OS X: `Cmd+i`), but you would have lost the specific indentation of the conditions/expressions:
+
[source,clojure]
----
(defn foo [bar baz]
  (cond
    cond1
    expr1
    cond2
    expr2
    :else
    default-expr))
----

==== More intuitive Ctrl+Enter
Hitting kbd:[Ctrl+Enter] when the cursor is located at the top level selects the preceding top level form to be sent to the REPL. Only when the cursor is right in front of a top level form will it be selected instead of the previous one. (Fix Issue #580)

e.g. if the caret is materialized with the symbol `|`:

[source,clojure]
----
(defn foo [] ...)|
(defn bar [] ....)
;; => foo's declaration will be sent to the REPL
(defn baz [] ...)
|(defn qix [] ...)
;; => qix's declaration will be sent to the REPL
----

==== Slurp / Barf
Slurp and Barf, 2 important paredit/structural manipulation features, have been added to the Editor. (Fixes Issue #486: Add support for barfage and slurpage)
+
See the Keybindings documentation for Slurp / Barf : https://code.google.com/p/counterclockwise/wiki/EditorKeyBindingsFeatures

- Fixed wrong keybinding for switching Rainbow Parens: "Cmd+( R" instead of "Cmd+(+R" (replace Cmd by Ctrl for Windows/Linux ; space indicates that you first type Cmd+(, then type R)

- Changed "toggle line comments" behaviour: before, if the selection had both commented and uncommented lines, it was an ambiguous case resolved by just doing nothing. Now, it is resolved by counting the number of commented and uncommented lines. If the number of uncommented lines in the selection is equal or greater than the number of commented lines, then those uncommented lines are commented. If the number of commented lines is greater than the number of uncommented lines, those commented lines are uncommented.
+
Calling "toggle lines comments" on the following code selection:
+
[source,clojure]
----
;(defn foo [....])
(defn bar [....])
(defn baz [....])
----
+
will result in:
+
[source,clojure]
----
;(defn foo [....])
;(defn bar [....])
;(defn baz [....])
----
+
But calling "toggle lines comments" on this code selection:
[source,clojure]
----
;(defn foo [....])
(defn bar [....])
;(defn baz [....])
----
+
will result in:
[source,clojure]
----
(defn foo [....])
(defn bar [....])
(defn baz [....])
----

- Auto indentation of a cond form changed: (Fixes #592)
+
[source,clojure]
----
;; from 
(cond test1 expr1
  test2 expr2)
;; to
(cond test1 expr1
      test2 expr2)
----

- Experimental Feature: enabling auto-reevaluation of last command typed in the REPL, after a successful evaluation from the Editor
* when the "repeat last expression" REPL command is active
* when the user sends a form tom evaluate to the REPL
* if the form evaluated without error
* then the last expression evaluated from the REPL input is evaluated again
+
A common usecase for this is while you're defining a function in the Editor and you want to repeat the same test expression again and again until it passes. The workflow then becomes:
+
** define the function in the editor, eval via Cmd+Enter
** switch to the REPL, enter a test expression, send the test expression via Cmd+Enter
** Click on the "Repeat last evaluation ..." button in the REPL
** switch to the editor, modify the function, eval via Cmd+Enter ... when the eval succeeds, the last expression entered in the REPl is reevaluated ... repeat ...


=== Repl 

- A bug had slipped in the project classpath management preventing native libraries to load properly, for instance when trying to work with Overtone. Fix Issue #577 

- Reverting the behaviour of the "Evaluate selection" when sending to the REPL : back to using 'in-ns instead of 'ns while transitioning to the selection's namespace
Fixes Issue #533: ns is sent to REPL instead of in-ns

- Launch repl ack timeout set to 60 sec instead of 30

- Better IPv6 support: replaced "localhost" occurences by "127.0.0.1"

- "Quiet command report mode" Preference has been removed. Now considered always ON by default. So always quiet.

=== Stability

- There were reports of restart issues after Eclipse crashes. Hopefully this has been improved in this release (Fix Issue #568	CCW Beta 0.13.0.201304190010 prevents Eclipse from loading)

=== Leiningen

- Internally switched to Leiningen 2.1.2

- Better exception reporting in the Problem Markers, e.g. when a dependency cannot be found, etc.

=== Better plays as an Eclipse plugin

- CCW plugin does not start unnecessarily when invoking the project's contextual menu

