= Counterclockwise ChangeLog 
Laurent Petit <laurent dot petit at gmail dot com>
:sectanchors:
:sectlinks:
:source-highlighter: coderay
:experimental:
:toc: 
:toc-title!:
:toclevels: 1

== Changes between Counterclockwise 0.12.3 and 0.20.0

`0.20.0` released on October 10, 2013

=== TL;DR

- `0.20.0` introduces **no breaking change**
- New Software Update Site http://updatesite.ccw-ide.org/stable
- Editor: new awesome `autoshift` feature, slurp/barf paredit commands support
- Lots of changes to fix stability concerns and various issues

=== Build Process totally rewritten

For people wanting to build Counterclockwise from scratch, or to work with Counterclockwise.

The Build Process now uses http://maven.apache.org[Maven] + http://www.eclipse.org/tycho[Tycho].

- It is now fully automated, from fetching Eclipse or non Eclipse dependencies, to building an update site for the codebase, to building Standalone Counterclockwise products for the codebase.

In a nutshell:

  git clone https://github.com/laurentpetit/ccw
  cd ccw
  mvn verify
  cd ccw.product/target/products # the products for Windows / Linux / OS X
  cd ../../../ccw.updatesite/target/repository # the Software Update Site 

For more information on installing a full-fledged dev environment, see the Wiki Page https://code.google.com/p/counterclockwise/wiki/HowToBuild[How To Build]

=== New Software Update Site

The software update site has been updated to its new location:

- Stable Versions: http://updatesite.ccw-ide.org/stable
- Beta Versions: http://updatesite.ccw-ide.org/beta

For more information on the available Software Update Sites and their retention policies, and more, see the Wiki Page https://code.google.com/p/counterclockwise/wiki/UpdateSites[Update Sites]

=== Editor

==== Reindent Selection
Reindent Selection has been implemented. Trigger it via `Ctrl+i` on Windows/Linux, `Cmd+i` on OSX.

==== Autoshift
While you type, the code on the following lines which depends upon the code on the current line is shifted to the right or to the left. More spaces/less spaces are added/removed automatically.

* For instance, if you have the following manually indented code (note that the call to the `cond` macro is indented 4 extra spaces to the right):
+
[source,clojure]
(defn foo [bar baz]
       (cond
         cond1
           expr1
         cond2
           expr2
         :else
           default-expr))

* You can fix the whole indentation by either placing the cursor anywhere in the `(cond` line and typing Tab, or in front of `(cond` and typing Backspace 2 times:
+
[source,clojure]
(defn foo [bar baz]
  (cond
    cond1
      expr1
    cond2
      expr2
    :else
      default-expr))

* Before the AutoShift feature, you would either have to indent each line manually, or select the whole `(cond..)` form and type `Ctrl+i` (OS X: `Cmd+i`), but you would have lost the specific indentation of the conditions/expressions:
+
[source,clojure]
----
(defn foo [bar baz]
  (cond
    cond1
    expr1
    cond2
    expr2
    :else
    default-expr))
----

==== More intuitive Ctrl+Enter
Hitting kbd:[Ctrl+Enter] when the cursor is located at the top level selects the preceding top level form to be sent to the REPL. Only when the cursor is right in front of a top level form will it be selected instead of the previous one. (Fix Issue #580)

e.g. if the caret is materialized with the symbol `|`:

[source,clojure]
----
(defn foo [] ...)|
(defn bar [] ....)
;; => foo's declaration will be sent to the REPL
(defn baz [] ...)
|(defn qix [] ...)
;; => qix's declaration will be sent to the REPL
----

==== Slurp / Barf
Slurp and Barf, 2 important paredit/structural manipulation features, have been added to the Editor. (Fixes Issue #486: Add support for barfage and slurpage)
+
See the Keybindings documentation for Slurp / Barf : https://code.google.com/p/counterclockwise/wiki/EditorKeyBindingsFeatures

- Fixed wrong keybinding for switching Rainbow Parens: "Cmd+( R" instead of "Cmd+(+R" (replace Cmd by Ctrl for Windows/Linux ; space indicates that you first type Cmd+(, then type R)

- Changed "toggle line comments" behaviour: before, if the selection had both commented and uncommented lines, it was an ambiguous case resolved by just doing nothing. Now, it is resolved by counting the number of commented and uncommented lines. If the number of uncommented lines in the selection is equal or greater than the number of commented lines, then those uncommented lines are commented. If the number of commented lines is greater than the number of uncommented lines, those commented lines are uncommented.
+
Calling "toggle lines comments" on the following code selection:
+
[source,clojure]
----
;(defn foo [....])
(defn bar [....])
(defn baz [....])
----
+
will result in:
+
[source,clojure]
----
;(defn foo [....])
;(defn bar [....])
;(defn baz [....])
----
+
But calling "toggle lines comments" on this code selection:
[source,clojure]
----
;(defn foo [....])
(defn bar [....])
;(defn baz [....])
----
+
will result in:
[source,clojure]
----
(defn foo [....])
(defn bar [....])
(defn baz [....])
----

- Auto indentation of a cond form changed: (Fixes #592)
+
[source,clojure]
----
;; from 
(cond test1 expr1
  test2 expr2)
;; to
(cond test1 expr1
      test2 expr2)
----

- Experimental Feature: enabling auto-reevaluation of last command typed in the REPL, after a successful evaluation from the Editor
* when the "repeat last expression" REPL command is active
* when the user sends a form tom evaluate to the REPL
* if the form evaluated without error
* then the last expression evaluated from the REPL input is evaluated again
+
A common usecase for this is while you're defining a function in the Editor and you want to repeat the same test expression again and again until it passes. The workflow then becomes:
+
** define the function in the editor, eval via Cmd+Enter
** switch to the REPL, enter a test expression, send the test expression via Cmd+Enter
** Click on the "Repeat last evaluation ..." button in the REPL
** switch to the editor, modify the function, eval via Cmd+Enter ... when the eval succeeds, the last expression entered in the REPl is reevaluated ... repeat ...


=== Repl 

- A bug had slipped in the project classpath management preventing native libraries to load properly, for instance when trying to work with Overtone. Fix Issue #577 

- Reverting the behaviour of the "Evaluate selection" when sending to the REPL : back to using 'in-ns instead of 'ns while transitioning to the selection's namespace
Fixes Issue #533: ns is sent to REPL instead of in-ns

- Launch repl ack timeout set to 60 sec instead of 30

- Better IPv6 support: replaced "localhost" occurences by "127.0.0.1"

- "Quiet command report mode" Preference has been removed. Now considered always ON by default. So always quiet.

=== Stability

- There were reports of restart issues after Eclipse crashes. Hopefully this has been improved in this release (Fix Issue #568	CCW Beta 0.13.0.201304190010 prevents Eclipse from loading)

=== Leiningen

- Internally switched to Leiningen 2.1.2

- Better exception reporting in the Problem Markers, e.g. when a dependency cannot be found, etc.

=== Better plays as an Eclipse plugin

- CCW plugin does not start unnecessarily when invoking the project's contextual menu

