= How to contribute to Counterclockwise development
Laurent Petit <laurent dot petit at gmail dot com>
:source-highlighter: coderay
:experimental:
:toc: 
:toc-title!:
:toclevels: 2

This page focuses on how to contribute code to Counterclockwise.

== General workflow

- Wave your hand on the mailing list to inform people of what you have in mind.
- Then at some point (when the discussion on the mailing list switches from discussing the relevance of the new proposed feature to specification / implementation detail) create an issue on Github. This will allow to narrow the focus on the feature, and keep track of the discussion. Mention the created issue on the mailing list thread
- Create a new branch to host development of code for the issue. Create a pull request, mention the pull request in the issue comments.
- Once discussion starts on the pull request, stop rewriting its history to help all people involved see the changes to the branch codebase that the discussion triggers.
- Never work on several issues in a same branch (and so never create several Pull Requests for the same branch).
- Always start new branches off the master branch (never off of another issue branch).
- When the PR is ready, reviewed and accepted, it is time to merge. There's nothing wrong in keeping the history of the commits. Rebasing / rewriting history just before merging the branch is possible, but is not totally error prone, so think about it twice before doing it and please be careful.

You can see the Github Flow page for a visual version of the workflow: https://guides.github.com/introduction/flow/


== Developing within Eclipse

=== Prerequisites
 
- Java 7
- Maven >= 3.1.1
** download from http://mirrors.linsrv.net/apache/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.zip
** unzip somewhere, e.g. `/path/to/maven`, create an environment variable `M2_HOME=/path/to/maven`, add `$M2_HOME/bin` to your path
- `Eclipse IDE for Java and DSL Developers` Luna sr1 (4.4.1) https://eclipse.org/downloads/packages/eclipse-ide-java-and-dsl-developers/lunasr1
** This packaging is preferred because it's the one embedding the more eclipse source code packages out of the box (see https://www.eclipse.org/downloads/compare.php?release=luna )


=== Install & Configure

- Clone CCW Repository 
** https://github.com/laurentpetit/ccw
- In Eclipse, import the repository projects (`ccw.aggregator`, `ccw.branding`, `ccw.core`, `ccw.core.test`, `ccw.feature`, `ccw.parent`, `ccw.product`, `doc`, `paredit.clj`)
- cd into `ccw.core` and invoke `mvn clean verify`
** This will install all CCW dependencies in folder `ccw.core/lib/`
** The operation must be be repeated after each update of `ccw.core` dependencies

=== Run a Test CCW environment

The following launch configuration files automatically install themselves in the "Run/Debug" Toolbar items as Shortcuts:

- `Counterclockwise Plugin` for Debugging the Plugin by launching it in the current PDE Target (shortcut for `ccw.core/Counterclockwise Plugin.launch`)
- `Counterclockwise Product` for Debugging the Standalone Product (shortcut for `ccw.core/Counterclockwise Product.launch`)
- `Counterclockwise Product Tests` for Launching the JUnit (SWTBot) tests (some tests don't pass in this mode) (shortcut for `ccw.core.test/Counterclockwise Product Tests.launch`)


== From the Command Line

=== Compile / Test / Package

----
git clone https://github.com/laurentpetit/ccw
cd ccw

# Clean + compile + unit test + integration test + build updatesite 
# + build Windows / Linux / OS X standalone products + build documentation:
mvn clean verify

# Compile + tests but no product(s) built (less time to complete):
# This deactivates the `luna` profile which deactivates the `ccw.product` module
mvn verify -P \!luna

# Same as above, but skipping launching tests:
mvn clean verify -DskipTests

# To only launch tests
mvn clean test
----

The products will be available in folder `ccw.product/target/products`

== Manage Version Numbers

The script `script/set-version.sh` updates `POMs`, `MANIFESTs` and `feature.xml` :

----
# If you want to set version to 0.20.0-SNAPSHOT
$ cd ccw
ccw$ script/set-version.sh 0.20.0-SNAPSHOT
----

== Adding clojure.test based tests

- Add the test namespace in `ccw.core.test/src/clj` using the usual namespace structure for folders
- Add the namespace to the list of namespaces to be tested in the java file `ccw.core.test/src/java/ccw/core/ClojureTests.java`

== Make CCW depend on a new feature

- Add the new feature dependency to the product definition in file `ccw.product/ccw.product`. See https://github.com/laurentpetit/ccw/blob/v0.31.1.STABLE001/ccw.product/ccw.product#L270
- If the new feature is not already provided by the p2 repositories known to the build, you'll need to add its repository to file `ccw.parent/pom.xml`. See https://github.com/laurentpetit/ccw/blob/v0.31.1.STABLE001/ccw.parent/pom.xml#L63


= Version Release Checklist

- Determine the new version number
- Update the Changelog note
- Mark the issues as Fixed
- Determine the versions of the dependencies to use
- if required, cut new versions for these
** ccw-server for instance
- Upgrade the version numbers
- Commit and tag
----
    # Edit Changelog then...
    ./script/set-number 3.4.9.STABLE001
    git commit -a -m"chore(mvn): Version 3.4.9.STABLE001"
    git tag "v3.4.9.STABLE001"
----
- Push, let Jenkins build
----
    git push laurentpetit master --tags
----
- Update the Eclipse Market Place
- Update Google code's project home page
- Update http://updatesite.ccw-ide.org/stable and beta (content.xml and artifacts.xml)
- Update http://doc.ccw-ide.org
- Update http://standalone.ccw-ide.org
- Drop an email to users and dev list
- Twit about it (mention #Counterclockwise and #Clojure)
- Upgrade the version number for the new SNAPSHOTS, commit
----
    # Edit Changelog then...
    ./script/set-number 3.4.10-SNAPSHOT
    git commit -a -m"chore(mvn): Upgrade version to 3.4.10-SNAPSHOT"
----

= References

- http://software.2206966.n2.nabble.com/Good-solution-for-non-osgi-jars-td5098103.html : original idea for using maven-dependency-plugin to copy deps into `lib/`
- https://github.com/reficio/p2-maven-plugin : easy to grok tutorial for beginning with maven tycho
- https://maven.apache.org/plugins/maven-dependency-plugin/copy-mojo.html : maven `dependency:copy` reference
- https://maven.apache.org/plugins/maven-dependency-plugin/unpack-dependencies-mojo.html : maven `dependency:unpack-dependencies` reference

