Counterclockwise Documentation Site
===================================
Laurent Petit <laurent.petit@gmail.com>
:highlight: highlightjs
:experimental:

Welcome to Counterclockwise's Documentation Site.

Counterclockwise is best described as an Integrated Development Environment for the http://www.clojure.org[Clojure] language. +
It is an extension of the popular http://www.eclipse.org[Eclipse IDE].

== Install


You don't have Eclipse and want to get up and running quickly? Download the *Standalone Product (batteries included)*, Follow link:documentation.html#install-as-standalone-product[Install Counterclockwise as a standalone product]

You have Eclipse and want to install Counterclockwise as an *Eclipse plugin*, Follow link:documentation.html#install-as-plugin[Install Counterclockwise as a plugin]

== User Documentation

*Where's a comprehensive documentation of Counterclockwise?* Follow link:documentation.html[Counterclockwise User Documentation].

*What's new?* Follow link:ChangeLog.html[ChangeLog of Counterclockwise Versions] to know everything.

*Keyboard Shortcut Cheat Sheet* link:keyboard-shortcuts.html[Keyboard Shorcuts]

== Developer Documentation

*Want to contribute to the development of Counterclockwise?* Start here for link:CONTRIBUTING.html[Installing an Environment to develop Counterclockwise itself].

